// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTERSTYPE_FBS_BANDAI_SIV_GAME_BIN_INPUT_H_
#define FLATBUFFERS_GENERATED_MONSTERSTYPE_FBS_BANDAI_SIV_GAME_BIN_INPUT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

namespace fbs_bandai_siv_game_bin_input {

struct monster;
struct monsterBuilder;

struct monsters_type;
struct monsters_typeBuilder;

struct monster FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef monsterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MONSTER_TYPE = 4,
    VT_NAME = 6,
    VT_HP = 8,
    VT_SPEED = 10,
    VT_COLOR0 = 12,
    VT_COLOR1 = 14,
    VT_COLOR2 = 16,
    VT_SCALE = 18,
    VT_MONSTER_ATTACK_WORDS_TYPE = 20,
    VT_MONSTER_WAS_HIT_WORDS_TYPE = 22
  };
  const flatbuffers::String *monster_type() const {
    return GetPointer<const flatbuffers::String *>(VT_MONSTER_TYPE);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 10);
  }
  int16_t speed() const {
    return GetField<int16_t>(VT_SPEED, 1);
  }
  float color0() const {
    return GetField<float>(VT_COLOR0, 0.8f);
  }
  float color1() const {
    return GetField<float>(VT_COLOR1, 0.6f);
  }
  float color2() const {
    return GetField<float>(VT_COLOR2, 0.4f);
  }
  float scale() const {
    return GetField<float>(VT_SCALE, 1.0f);
  }
  const flatbuffers::String *monster_attack_words_type() const {
    return GetPointer<const flatbuffers::String *>(VT_MONSTER_ATTACK_WORDS_TYPE);
  }
  const flatbuffers::String *monster_was_hit_words_type() const {
    return GetPointer<const flatbuffers::String *>(VT_MONSTER_WAS_HIT_WORDS_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MONSTER_TYPE) &&
           verifier.VerifyString(monster_type()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int16_t>(verifier, VT_HP, 2) &&
           VerifyField<int16_t>(verifier, VT_SPEED, 2) &&
           VerifyField<float>(verifier, VT_COLOR0, 4) &&
           VerifyField<float>(verifier, VT_COLOR1, 4) &&
           VerifyField<float>(verifier, VT_COLOR2, 4) &&
           VerifyField<float>(verifier, VT_SCALE, 4) &&
           VerifyOffset(verifier, VT_MONSTER_ATTACK_WORDS_TYPE) &&
           verifier.VerifyString(monster_attack_words_type()) &&
           VerifyOffset(verifier, VT_MONSTER_WAS_HIT_WORDS_TYPE) &&
           verifier.VerifyString(monster_was_hit_words_type()) &&
           verifier.EndTable();
  }
};

struct monsterBuilder {
  typedef monster Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_monster_type(flatbuffers::Offset<flatbuffers::String> monster_type) {
    fbb_.AddOffset(monster::VT_MONSTER_TYPE, monster_type);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(monster::VT_NAME, name);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(monster::VT_HP, hp, 10);
  }
  void add_speed(int16_t speed) {
    fbb_.AddElement<int16_t>(monster::VT_SPEED, speed, 1);
  }
  void add_color0(float color0) {
    fbb_.AddElement<float>(monster::VT_COLOR0, color0, 0.8f);
  }
  void add_color1(float color1) {
    fbb_.AddElement<float>(monster::VT_COLOR1, color1, 0.6f);
  }
  void add_color2(float color2) {
    fbb_.AddElement<float>(monster::VT_COLOR2, color2, 0.4f);
  }
  void add_scale(float scale) {
    fbb_.AddElement<float>(monster::VT_SCALE, scale, 1.0f);
  }
  void add_monster_attack_words_type(flatbuffers::Offset<flatbuffers::String> monster_attack_words_type) {
    fbb_.AddOffset(monster::VT_MONSTER_ATTACK_WORDS_TYPE, monster_attack_words_type);
  }
  void add_monster_was_hit_words_type(flatbuffers::Offset<flatbuffers::String> monster_was_hit_words_type) {
    fbb_.AddOffset(monster::VT_MONSTER_WAS_HIT_WORDS_TYPE, monster_was_hit_words_type);
  }
  explicit monsterBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<monster> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<monster>(end);
    return o;
  }
};

inline flatbuffers::Offset<monster> Createmonster(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> monster_type = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int16_t hp = 10,
    int16_t speed = 1,
    float color0 = 0.8f,
    float color1 = 0.6f,
    float color2 = 0.4f,
    float scale = 1.0f,
    flatbuffers::Offset<flatbuffers::String> monster_attack_words_type = 0,
    flatbuffers::Offset<flatbuffers::String> monster_was_hit_words_type = 0) {
  monsterBuilder builder_(_fbb);
  builder_.add_monster_was_hit_words_type(monster_was_hit_words_type);
  builder_.add_monster_attack_words_type(monster_attack_words_type);
  builder_.add_scale(scale);
  builder_.add_color2(color2);
  builder_.add_color1(color1);
  builder_.add_color0(color0);
  builder_.add_name(name);
  builder_.add_monster_type(monster_type);
  builder_.add_speed(speed);
  builder_.add_hp(hp);
  return builder_.Finish();
}

inline flatbuffers::Offset<monster> CreatemonsterDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *monster_type = nullptr,
    const char *name = nullptr,
    int16_t hp = 10,
    int16_t speed = 1,
    float color0 = 0.8f,
    float color1 = 0.6f,
    float color2 = 0.4f,
    float scale = 1.0f,
    const char *monster_attack_words_type = nullptr,
    const char *monster_was_hit_words_type = nullptr) {
  auto monster_type__ = monster_type ? _fbb.CreateString(monster_type) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto monster_attack_words_type__ = monster_attack_words_type ? _fbb.CreateString(monster_attack_words_type) : 0;
  auto monster_was_hit_words_type__ = monster_was_hit_words_type ? _fbb.CreateString(monster_was_hit_words_type) : 0;
  return fbs_bandai_siv_game_bin_input::Createmonster(
      _fbb,
      monster_type__,
      name__,
      hp,
      speed,
      color0,
      color1,
      color2,
      scale,
      monster_attack_words_type__,
      monster_was_hit_words_type__);
}

struct monsters_type FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef monsters_typeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MONSTERS_DATA = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>> *monsters_data() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>> *>(VT_MONSTERS_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MONSTERS_DATA) &&
           verifier.VerifyVector(monsters_data()) &&
           verifier.VerifyVectorOfTables(monsters_data()) &&
           verifier.EndTable();
  }
};

struct monsters_typeBuilder {
  typedef monsters_type Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_monsters_data(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>>> monsters_data) {
    fbb_.AddOffset(monsters_type::VT_MONSTERS_DATA, monsters_data);
  }
  explicit monsters_typeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<monsters_type> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<monsters_type>(end);
    return o;
  }
};

inline flatbuffers::Offset<monsters_type> Createmonsters_type(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>>> monsters_data = 0) {
  monsters_typeBuilder builder_(_fbb);
  builder_.add_monsters_data(monsters_data);
  return builder_.Finish();
}

inline flatbuffers::Offset<monsters_type> Createmonsters_typeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>> *monsters_data = nullptr) {
  auto monsters_data__ = monsters_data ? _fbb.CreateVector<flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monster>>(*monsters_data) : 0;
  return fbs_bandai_siv_game_bin_input::Createmonsters_type(
      _fbb,
      monsters_data__);
}

inline const fbs_bandai_siv_game_bin_input::monsters_type *Getmonsters_type(const void *buf) {
  return flatbuffers::GetRoot<fbs_bandai_siv_game_bin_input::monsters_type>(buf);
}

inline const fbs_bandai_siv_game_bin_input::monsters_type *GetSizePrefixedmonsters_type(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fbs_bandai_siv_game_bin_input::monsters_type>(buf);
}

inline bool Verifymonsters_typeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fbs_bandai_siv_game_bin_input::monsters_type>(nullptr);
}

inline bool VerifySizePrefixedmonsters_typeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fbs_bandai_siv_game_bin_input::monsters_type>(nullptr);
}

inline void Finishmonsters_typeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monsters_type> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedmonsters_typeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fbs_bandai_siv_game_bin_input::monsters_type> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fbs_bandai_siv_game_bin_input

#endif  // FLATBUFFERS_GENERATED_MONSTERSTYPE_FBS_BANDAI_SIV_GAME_BIN_INPUT_H_
